export function UnderlineBox({children, innerText='Hover Me'}){
    return <div className={`relative w-fit flex items-center justify-center after:content-[''] after:absolute after:border-2 after:rounded-full after:w-0 sm:hover:after:w-full max-sm:active:after:w-full px-2 after:top-full after:opacity-0 sm:hover:after:opacity-100 max-sm:active:after:opacity-100 after:transition-all sm:duration-200`}>
        {innerText} {children}
    </div>
}

export function Navicon(){
    return <div className="relative flex z-30 flex-col items-center justify-center gap-[4px] hover:w-10 w-8 h-8 transition-all duration-300 active:w-7 opacity-70 hover:opacity-100 cursor-pointer" >
        <div className="navIcon w-[80%] left-0 absolute border-2 border-[var(--text)] items-start justify-center rounded-full after:content-[''] after:absolute after:left-0 after:border-2 after:border-[var(--text)] after:w-[60%] after:bottom-2 after:rounded-full before:content-[''] before:w-[60%] before:rounded-full before:absolute before:border-2 before:border-[var(--text)] before:right-0 before:top-2"></div>
    </div>
}

export function HoverBox({children, className=''}){
    return <div className={`${className} max-sm:active:bg-[var(--bgSec)] sm:hover:bg-[var(--bgSec)] size-9 rounded-md flex items-center justify-center relative p-2 cursor-pointer`}>
        {children}
    </div>
}

export function Box({children}){
    return <div className={`${className} bg-[var(--bgSec)] opacity-80 max-sm:active:opacity-100 sm:hover:opacity-100 size-9 rounded-md flex items-center justify-center relative p-2 cursor-pointer`}>
        {children}
    </div>
}

function Ex(){
    return <div>
        
        <hr className=" bg-slate-50" />
        <hr className=" bg-gray-50" />
        <hr className=" bg-zinc-50" />
        <hr className=" bg-neutral-50" />
        <hr className=" bg-stone-50" />
        <hr className=" bg-red-50" />
        <hr className=" bg-orange-50" />
        <hr className=" bg-amber-50" />
        <hr className=" bg-yellow-50" />
        <hr className=" bg-lime-50" />
        <hr className=" bg-green-50" />
        <hr className=" bg-emerald-50" />
        <hr className=" bg-teal-50" />
        <hr className=" bg-cyan-50" />
        <hr className=" bg-sky-50" />
        <hr className=" bg-blue-50" />
        <hr className=" bg-indigo-50" />
        <hr className=" bg-violet-50" />
        <hr className=" bg-purple-50" />
        <hr className=" bg-fuchsia-50" />
        <hr className=" bg-pink-50" />
        <hr className=" bg-rose-50" />
        <hr className=" bg-slate-100" />
        <hr className=" bg-gray-100" />
        <hr className=" bg-zinc-100" />
        <hr className=" bg-neutral-100" />
        <hr className=" bg-stone-100" />
        <hr className=" bg-red-100" />
        <hr className=" bg-orange-100" />
        <hr className=" bg-amber-100" />
        <hr className=" bg-yellow-100" />
        <hr className=" bg-lime-100" />
        <hr className=" bg-green-100" />
        <hr className=" bg-emerald-100" />
        <hr className=" bg-teal-100" />
        <hr className=" bg-cyan-100" />
        <hr className=" bg-sky-100" />
        <hr className=" bg-blue-100" />
        <hr className=" bg-indigo-100" />
        <hr className=" bg-violet-100" />
        <hr className=" bg-purple-100" />
        <hr className=" bg-fuchsia-100" />
        <hr className=" bg-pink-100" />
        <hr className=" bg-rose-100" />
        <hr className=" bg-slate-200" />
        <hr className=" bg-gray-200" />
        <hr className=" bg-zinc-200" />
        <hr className=" bg-neutral-200" />
        <hr className=" bg-stone-200" />
        <hr className=" bg-red-200" />
        <hr className=" bg-orange-200" />
        <hr className=" bg-amber-200" />
        <hr className=" bg-yellow-200" />
        <hr className=" bg-lime-200" />
        <hr className=" bg-green-200" />
        <hr className=" bg-emerald-200" />
        <hr className=" bg-teal-200" />
        <hr className=" bg-cyan-200" />
        <hr className=" bg-sky-200" />
        <hr className=" bg-blue-200" />
        <hr className=" bg-indigo-200" />
        <hr className=" bg-violet-200" />
        <hr className=" bg-purple-200" />
        <hr className=" bg-fuchsia-200" />
        <hr className=" bg-pink-200" />
        <hr className=" bg-rose-200" />
        <hr className=" bg-slate-300" />
        <hr className=" bg-gray-300" />
        <hr className=" bg-zinc-300" />
        <hr className=" bg-neutral-300" />
        <hr className=" bg-stone-300" />
        <hr className=" bg-red-300" />
        <hr className=" bg-orange-300" />
        <hr className=" bg-amber-300" />
        <hr className=" bg-yellow-300" />
        <hr className=" bg-lime-300" />
        <hr className=" bg-green-300" />
        <hr className=" bg-emerald-300" />
        <hr className=" bg-teal-300" />
        <hr className=" bg-cyan-300" />
        <hr className=" bg-sky-300" />
        <hr className=" bg-blue-300" />
        <hr className=" bg-indigo-300" />
        <hr className=" bg-violet-300" />
        <hr className=" bg-purple-300" />
        <hr className=" bg-fuchsia-300" />
        <hr className=" bg-pink-300" />
        <hr className=" bg-rose-300" />
        <hr className=" bg-slate-400" />
        <hr className=" bg-gray-400" />
        <hr className=" bg-zinc-400" />
        <hr className=" bg-neutral-400" />
        <hr className=" bg-stone-400" />
        <hr className=" bg-red-400" />
        <hr className=" bg-orange-400" />
        <hr className=" bg-amber-400" />
        <hr className=" bg-yellow-400" />
        <hr className=" bg-lime-400" />
        <hr className=" bg-green-400" />
        <hr className=" bg-emerald-400" />
        <hr className=" bg-teal-400" />
        <hr className=" bg-cyan-400" />
        <hr className=" bg-sky-400" />
        <hr className=" bg-blue-400" />
        <hr className=" bg-indigo-400" />
        <hr className=" bg-violet-400" />
        <hr className=" bg-purple-400" />
        <hr className=" bg-fuchsia-400" />
        <hr className=" bg-pink-400" />
        <hr className=" bg-rose-400" />
        <hr className=" bg-slate-500" />
        <hr className=" bg-gray-500" />
        <hr className=" bg-zinc-500" />
        <hr className=" bg-neutral-500" />
        <hr className=" bg-stone-500" />
        <hr className=" bg-red-500" />
        <hr className=" bg-orange-500" />
        <hr className=" bg-amber-500" />
        <hr className=" bg-yellow-500" />
        <hr className=" bg-lime-500" />
        <hr className=" bg-green-500" />
        <hr className=" bg-emerald-500" />
        <hr className=" bg-teal-500" />
        <hr className=" bg-cyan-500" />
        <hr className=" bg-sky-500" />
        <hr className=" bg-blue-500" />
        <hr className=" bg-indigo-500" />
        <hr className=" bg-violet-500" />
        <hr className=" bg-purple-500" />
        <hr className=" bg-fuchsia-500" />
        <hr className=" bg-pink-500" />
        <hr className=" bg-rose-500" />
        <hr className=" bg-slate-600" />
        <hr className=" bg-gray-600" />
        <hr className=" bg-zinc-600" />
        <hr className=" bg-neutral-600" />
        <hr className=" bg-stone-600" />
        <hr className=" bg-red-600" />
        <hr className=" bg-orange-600" />
        <hr className=" bg-amber-600" />
        <hr className=" bg-yellow-600" />
        <hr className=" bg-lime-600" />
        <hr className=" bg-green-600" />
        <hr className=" bg-emerald-600" />
        <hr className=" bg-teal-600" />
        <hr className=" bg-cyan-600" />
        <hr className=" bg-sky-600" />
        <hr className=" bg-blue-600" />
        <hr className=" bg-indigo-600" />
        <hr className=" bg-violet-600" />
        <hr className=" bg-purple-600" />
        <hr className=" bg-fuchsia-600" />
        <hr className=" bg-pink-600" />
        <hr className=" bg-rose-600" />
        <hr className=" bg-slate-700" />
        <hr className=" bg-gray-700" />
        <hr className=" bg-zinc-700" />
        <hr className=" bg-neutral-700" />
        <hr className=" bg-stone-700" />
        <hr className=" bg-red-700" />
        <hr className=" bg-orange-700" />
        <hr className=" bg-amber-700" />
        <hr className=" bg-yellow-700" />
        <hr className=" bg-lime-700" />
        <hr className=" bg-green-700" />
        <hr className=" bg-emerald-700" />
        <hr className=" bg-teal-700" />
        <hr className=" bg-cyan-700" />
        <hr className=" bg-sky-700" />
        <hr className=" bg-blue-700" />
        <hr className=" bg-indigo-700" />
        <hr className=" bg-violet-700" />
        <hr className=" bg-purple-700" />
        <hr className=" bg-fuchsia-700" />
        <hr className=" bg-pink-700" />
        <hr className=" bg-rose-700" />
        <hr className=" bg-slate-800" />
        <hr className=" bg-gray-800" />
        <hr className=" bg-zinc-800" />
        <hr className=" bg-neutral-800" />
        <hr className=" bg-stone-800" />
        <hr className=" bg-red-800" />
        <hr className=" bg-orange-800" />
        <hr className=" bg-amber-800" />
        <hr className=" bg-yellow-800" />
        <hr className=" bg-lime-800" />
        <hr className=" bg-green-800" />
        <hr className=" bg-emerald-800" />
        <hr className=" bg-teal-800" />
        <hr className=" bg-cyan-800" />
        <hr className=" bg-sky-800" />
        <hr className=" bg-blue-800" />
        <hr className=" bg-indigo-800" />
        <hr className=" bg-violet-800" />
        <hr className=" bg-purple-800" />
        <hr className=" bg-fuchsia-800" />
        <hr className=" bg-pink-800" />
        <hr className=" bg-rose-800" />
        <hr className=" bg-slate-900" />
        <hr className=" bg-gray-900" />
        <hr className=" bg-zinc-900" />
        <hr className=" bg-neutral-900" />
        <hr className=" bg-stone-900" />
        <hr className=" bg-red-900" />
        <hr className=" bg-orange-900" />
        <hr className=" bg-amber-900" />
        <hr className=" bg-yellow-900" />
        <hr className=" bg-lime-900" />
        <hr className=" bg-green-900" />
        <hr className=" bg-emerald-900" />
        <hr className=" bg-teal-900" />
        <hr className=" bg-cyan-900" />
        <hr className=" bg-sky-900" />
        <hr className=" bg-blue-900" />
        <hr className=" bg-indigo-900" />
        <hr className=" bg-violet-900" />
        <hr className=" bg-purple-900" />
        <hr className=" bg-fuchsia-900" />
        <hr className=" bg-pink-900" />
        <hr className=" bg-rose-900" />
        <hr className=" bg-slate-950" />
        <hr className=" bg-gray-950" />
        <hr className=" bg-zinc-950" />
        <hr className=" bg-neutral-950" />
        <hr className=" bg-stone-950" />
        <hr className=" bg-red-950" />
        <hr className=" bg-orange-950" />
        <hr className=" bg-amber-950" />
        <hr className=" bg-yellow-950" />
        <hr className=" bg-lime-950" />
        <hr className=" bg-green-950" />
        <hr className=" bg-emerald-950" />
        <hr className=" bg-teal-950" />
        <hr className=" bg-cyan-950" />
        <hr className=" bg-sky-950" />
        <hr className=" bg-blue-950" />
        <hr className=" bg-indigo-950" />
        <hr className=" bg-violet-950" />
        <hr className=" bg-purple-950" />
        <hr className=" bg-fuchsia-950" />
        <hr className=" bg-pink-950" />
        <hr className=" bg-rose-950" />
    </div>
}